default: &default
  username: postgres
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  username: develop
  database: new_vision_development
test:
  adapter: postgresql
  database: new_vision_test
  pool: 5
  timeout: 5000

staging:
  <<: *default
  username: informat
  database: new_vision_staging

production:
  <<: *default
  username: informat
  database: new_vision_production
